### ISSUE TITLE
Would an SVG version by helpful?

### ISSUE THREAD

**Issue by joelanman** [abbott567/sketch_wireframing_kit#3]
If people don't have Sketch, would it be helpful to at least have access to SVG? This could be a simple export of the Sketch file.

**Comment by abbott567** [comment]
This is a really good idea. Do you think it would be better to export everything to one big artboard, or to have each element as its own SVG in a folder structure?

**Comment by abbott567** [comment]
Looks like exporting the entire .sketch file doesn't work. It tries to create images out of the yellow focus highlights (probably because they're implemented as sharp shadows in sketch). I'll move stuff over one element at a time into illustrator and redraw anything that's broken. This will allow a much better SVG export.

**Comment by joelanman** [comment]
that sounds like a lot of work! and you'd need to do it on every release? Is there not a quick fix to do it from sketch?

**Comment by abbott567** [comment]
It doesn't really export properly for some reason, it's creating random clip groups. For example, the line of text that reads 'Do you already have a personal user account?' isn't grouped as one item. It is several groups of random clusters such as 'you alread' then 'y' then 'have a persona' lol

![image](https://cloud.githubusercontent.com/assets/9450064/22736241/25002a3a-edf5-11e6-85fb-d9a617972f5a.png)

I guess it will be some work in the short term, in the long term it wont be so bad as most changes to the kit are relatively small. If it's going to help I'm happy to do the work.

**Comment by dashouse** [comment]
I would suggest exporting only the very basic stuff you'd need to quickly
assemble a page that would look like GOV.UK... e.g. header background /
logo / button etc

If this is being used for Axure then they will probably need to use the
native axure form elements anyway?

**Comment by abbott567** [comment]
I guess we need to know what elements people would need, if there is a need there at all. I can export to PDF from sketch in one go. That might work as a better open format.

**Comment by abbott567** [comment]
Closing this down as its been more than 12 months and there isn't strong evidence for an SVG version. It's a good idea but would take a lot to maintain, and unless it comes out as a real need I don't really have the time or effort to support it.
