### ISSUE TITLE
Could the kit include symbols for the GOV.UK Component Kit

### ISSUE THREAD

**Issue by henryhadlow** [abbott567/sketch_wireframing_kit#4]
Some of the stuff is included already, but some components are missing, for example, the option select.

http://govuk-component-guide.herokuapp.com/

**Comment by joelanman** [comment]
important to note those are components for GOV.UK Publisher, and not necessarily recommended for use elsewhere, whereas Elements and the Frontend Toolkit are mandated by the service manual.

**Comment by abbott567** [comment]
Are these .ERB? Presumably, these are specific components for some Ruby On Rails applications somewhere? Are they recognised patterns to be used in services?
